### PR TITLE
Update mypy2junit.py

### PR DESCRIPTION
**Pull request by gavrmike**
handle "1 error"
handle success

### CODE REVIEW

**Comment by dundee** [comment]
Hi,
thanks for the pull request!

Could you add test for this case? Thanks!

**Comment by gavrmike** [comment]
Hi, i added tests

**Comment by dundee** [comment]
Thanks!

**Comment by gavrmike** [comment]
Could you add new version to pypy?

**Comment by dundee** [comment]
Uploaded.

**Comment by gavrmike** [comment]
Thanks a lot!

**Pull request merged**
